// Maintenance helper: clean up failed/stale preview imports, broken timeline
// projects, and AI-generated compositions that errored out.
//
// Detection rule: a composition is "broken" if it failed its thumbnail
// generation AND its id matches one of the auto-generated patterns (Preview-*,
// TimelineProject-*, AIGen-*). User-created compositions are never touched.
const fs = require('fs');
const path = require('path');
const { listCompositions } = require('./compositions');
const thumbnails = require('./thumbnails');

const SRC_DIR = path.join(__dirname, '..', '..', 'src');
const IMPORTS_DIR = path.join(SRC_DIR, 'imports');
const ROOT_FILE = path.join(SRC_DIR, 'Root.tsx');

const AUTO_PATTERNS = [
  /^Preview-/,
  /^TimelineProject-/,
  /^AIGen-/
];

function isAutoGenerated(id) {
  return AUTO_PATTERNS.some(re => re.test(id));
}

// Return a list of ids considered broken — compositions whose thumbnails
// failed AND whose ids match auto-generated patterns.
function findBrokenAutoGenerated() {
  const thumbStatus = thumbnails.getStatus();
  const erroredIds = Object.keys(thumbStatus.errors || {});
  const compositions = listCompositions();
  return compositions
    .filter(c => isAutoGenerated(c.id) && erroredIds.includes(c.id))
    .map(c => c.id);
}

// Return all auto-generated compositions (whether broken or not) so the user
// can nuke the entire auto-generated pile if they want a clean slate.
function findAllAutoGenerated() {
  return listCompositions()
    .filter(c => isAutoGenerated(c.id))
    .map(c => c.id);
}

function cleanCompositionById(id) {
  const fileSlug = id.replace(/-/g, '');
  const filePath = path.join(IMPORTS_DIR, `${fileSlug}.tsx`);
  try { if (fs.existsSync(filePath)) fs.unlinkSync(filePath); } catch {}

  // Remove thumbnail PNG if any
  const thumbPath = thumbnails.thumbnailPath(id);
  try { if (fs.existsSync(thumbPath)) fs.unlinkSync(thumbPath); } catch {}

  // Remove import line and Composition block from Root.tsx
  let root = fs.readFileSync(ROOT_FILE, 'utf8');
  root = root.replace(new RegExp(`^import.*${fileSlug}.*\\n`, 'gm'), '');
  // Comment markers we use: Imported:, Timeline:, AIGen:
  const markerRe = new RegExp(`\\s*\\{\\s*/\\*\\s*(Imported|Timeline|AIGen):\\s*${id}\\s*\\*/\\s*\\}[\\s\\S]*?/>`, 'g');
  root = root.replace(markerRe, '');
  fs.writeFileSync(ROOT_FILE, root);
}

function cleanAll(ids) {
  const cleaned = [];
  ids.forEach(id => {
    try { cleanCompositionById(id); cleaned.push(id); }
    catch (err) { console.warn('[cleanup] failed for', id, err.message); }
  });
  return cleaned;
}

module.exports = {
  findBrokenAutoGenerated,
  findAllAutoGenerated,
  cleanCompositionById,
  cleanAll,
  isAutoGenerated
};
