// AUTO-GENERATED by daily-render.js - DO NOT EDIT
// Generated: 2026-04-10T10:18:10.505Z

import { staticFile } from "remotion";

export const DAILY_DATE = "2026-04-10";
export const DAILY_NUM_PROMPTS = 10;
export const DAILY_TOTAL_FRAMES = 6241;

export const DAILY_PROMPTS = [
  "An astronaut in a magenta, black, and white space suit floating in outer space, with Earth visible in the background, capturing the contrast of the vibrant colors against the dark universe.",
  "art line, techno, dark, gothic, darkness, surrealism",
  "stills archive, warner bros .com --c 15 --style raw --v 6",
  "A dramatic cinematic scene featuring two rival products placed side by side in a custom-designed environment that visually reflects their identities. The composition should include high contrast lighting, atmospheric effects like mist, fog, or neon glow, and hyper-detailed textures. Incorporate a powerful 3D slogan \"LET'S AI\" below or behind the products in bold stylized typography that fits the scene’s mood. The products must reflect the essence of XBOX and Playstation through color, lighting, and placement. Ultra-realistic, moody tones, with sharp depth of field and high resolution",
  "video game still, cdprojektred .com, cyberpunk 2077",
  "C0001.R3D: The most realistic photograph ever in the world, Authentic shot of a top model, professional photoshoot for Vogue Magazine, beautiful 24 year old woman with dark hair with highlights, blue eyes, behind the scenes of a major hollywood film, sitting in a director's chair",
  "A documentary-style photograph showcasing a young, attractive woman with brunette hair and blue eyes in a dystopian world. She is dressed in futuristic clothing, amidst a backdrop of futuristic, ruined buildings. The setting is during the 'blue hour,' adding a moody and evocative atmosphere. The woman is gazing into the distance, embodying a sense of contemplation or anticipation --ar 16:9 --style qUCGoMjEi",
  "The tennis player tries to control the burning tennis ball, but to no avail, The court is in a desert resembling Mars, The weather is amazingly stormy, d, superb cinematic color grading, key visual, HDR, film still, --ar 16:9",
  "live-action sports shot, fast-paced, POV style, a soccer player in the world cup, swiftly dribbling the baller and moving downfield to score a goal against the opposing team, in a big stadium with thousands of people in the stands cheering",
  "cinematic, ultra realistic, wide shot, Canon EOS R5 at f/2, HBO series, Game of Thrones, Emilia Clarke as her character Daenerys Targaryen",
];

export const DAILY_IMAGES = [
  staticFile("daily/img_1.jpg"),
  staticFile("daily/img_2.png"),
  staticFile("daily/img_3.png"),
  staticFile("daily/img_4.png"),
  staticFile("daily/img_5.png"),
  staticFile("daily/img_6.png"),
  staticFile("daily/img_7.png"),
  staticFile("daily/img_8.png"),
  staticFile("daily/img_9.png"),
  staticFile("daily/img_10.png"),
];

export const DAILY_VOICEOVERS = [
  staticFile("daily/vo_1.mp3"),
  staticFile("daily/vo_2.mp3"),
  staticFile("daily/vo_3.mp3"),
  staticFile("daily/vo_4.mp3"),
  staticFile("daily/vo_5.mp3"),
  staticFile("daily/vo_6.mp3"),
  staticFile("daily/vo_7.mp3"),
  staticFile("daily/vo_8.mp3"),
  staticFile("daily/vo_9.mp3"),
  staticFile("daily/vo_10.mp3"),
];

export const DAILY_CATEGORIES = [
  "Fantasy",
  "AI Influencer",
  "Cinematic",
  "Products",
  "Cinematic",
  "Cinematic",
  "Cinematic",
  "Cinematic",
  "Cinematic",
  "Cinematic",
];

export const DAILY_SECTION_FRAMES = [407, 234, 272, 1257, 251, 670, 894, 566, 521, 468];
export const DAILY_SECTION_STARTS = [315, 722, 956, 1228, 2485, 2736, 3406, 4300, 4866, 5387];

export const DAILY_INTRO_VO = staticFile("daily/vo_intro.mp3");
export const DAILY_OUTRO_VO = staticFile("daily/vo_outro.mp3");
